config/routes.rb
Dinovet::Application.routes.draw do
  root :to => "clients#index"

  resources :diagnosis_categories, :except => [:show]
  resources :diagnoses, :except => [:show]

  resources :treatment_categories, :except => [:show]
  resources :treatments, :except => [:show]

  resources :species, :only => [:show]

  resources :clients, :except => [:show] do
    resources :patients, :only => [:new, :create, :update]
  end

  resources :employees

  resources :patients, :only => [:edit, :update] do
    resources :events, :only => [:index]
    resources :diagnosis_events, :only => [:new, :create]
    resources :treatment_plans,  :only => [:new, :create]
  end

  resource :search, :only => [:show]

end

app/models/client.rb
class Client
  include Mongoid::Document
  include Mongoid::Timestamps
  include Sunspot::Mongoid
  field :first_name
  field :last_name
  field :address_1
  field :address_2
  field :city
  field :state
  field :zipcode
  field :email

  embeds_many :phone_numbers
  references_many :patients

  accepts_nested_attributes_for :phone_numbers, :allow_destroy => true

  validates_associated  :phone_numbers
  validates_presence_of :first_name, :last_name, :address_1, :city, :state,
                        :zipcode, :phone_numbers
  validates_format_of   :email, :allow_nil => true,
                        :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i

  searchable do
    text :first_name
    text :last_name
    text :address_1
    text :city
    text :state
    text :zipcode
    text :email
    text :phone_numbers do |client|
      client.phone_numbers.map { |phone_number| phone_number.number }
    end
  end

  def full_name
    "#{last_name}, #{first_name}"
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController

  def index
    @clients = Client.all
  end

  def new
    @client = Client.new
    @phone_numbers = @client.phone_numbers << PhoneNumber.new
  end

  def edit
    @client = Client.find(params[:id])
    @phone_numbers = @client.phone_numbers
  end

  def update
    @client = Client.find(params[:id])
    @phone_numbers = @client.phone_numbers

    if @client.update_attributes(params[:client])
      flash[:notice] = "Client updated successfully"
      respond_to do |format|
        format.js   { redirect_to edit_client_path(@client, :format => :js) }
        format.html { redirect_to edit_client_path(@client) }
      end
    else
      flash[:error] = "Failed to update client"
      respond_to do |format|
        format.js
        format.html { render :edit }
      end
    end
  end

  def create
    @client = Client.new(params[:client])
    @phone_numbers = @client.phone_numbers

    if @client.save
      flash[:notice] = "Client added successfully"
      respond_to do |format|
        format.js   { redirect_to edit_client_path(@client, :format => :js) }
        format.html { redirect_to edit_client_path(@client) }
      end
    else
      flash[:error] = "Failed to create client"
      respond_to do |format|
        format.js
        format.html { render :new }
      end
    end
  end

end

app/helpers/clients_helper.rb
module ClientsHelper
  def client_panel(client, &block)
    render :layout => 'layouts/panel',
      :locals => {
        :id => 'client',
        :title => "Client",
        :subtitle => client.full_name },
      &block
  end

  def clients_panel(&block)
    render :layout => 'layouts/panel',
      :locals => {
        :id => 'clients',
        :title => "Clients" },
      &block
  end

  def patient_select_list(client)
    patients = client.patients.map do |p|
      content_tag :li do
        link_to h(p.name), edit_patient_path(p), :remote => true
      end
    end

    content_tag :ul do
      patients.join.html_safe
    end
  end
end

app/views/clients/_client_item.html.haml
- client = client_item
%li
  %a{:href => edit_client_path(client)}= client.full_name

app/views/clients/_client_row.html.haml
- client = client_row
%tr
  %td= link_to client.full_name, edit_client_path(client)
  %td
    %small
      = address_for(client)
  %td
    %small
      = phone_numbers_for(client)
  %td
    - client.patients.each do |patient|
      = link_to patient.name, edit_patient_path(patient)
      != "&mdash;" unless patient == client.patients.last

app/views/clients/_edit.html.haml
= client_panel(@client) do
  = render 'clients/form', :client => @client, :phone_numbers => @phone_numbers

app/views/clients/_form.html.haml
= form_for client, :remote => true do |f|

  %fieldset
    %legend Name
    %ol
      %li
        = f.label :first_name
        = f.text_field :first_name, :autocomplete => :off
      %li
        = f.label :last_name
        = f.text_field :last_name, :autocomplete => :off

  %fieldset
    %legend Address
    %ol
      %li
        = f.label :address_1, "Address"
        = f.text_field :address_1, :autocomplete => :off
      %li
        = f.label :address_2, "Apt."
        = f.text_field :address_2, :autocomplete => :off
      %li
        = f.label :city
        = f.text_field :city, :autocomplete => :off
      %li
        = f.label :state
        = f.select :state, ['', 'New York']
      %li
        = f.label :zipcode
        = f.text_field :zipcode, :autocomplete => :off
      
  %fieldset{:class => 'phone'}
    %legend Phone
    %ol
      = f.fields_for :phone_numbers do |pf|
        = render 'phone_numbers/form', :f => pf
      %li
        %a{:href => '#', :class => 'add', :title => 'Add additional number'}
          = image_tag('add.png')
  %fieldset{:class => 'e-mail'}
    %legend E-Mail
    %ol
      %li
        = f.label :email, 'E-mail', :class => 'test'
        = f.text_field :email, :autocomplete => :off



  - unless client.new_record?
    = render 'clients/patient_list', :client => client

  %fieldset{:class => "submit"}
    = f.submit

app/views/clients/_new.html.haml
= client_panel(@client) do
  = render "form", :client => @client, :phone_numbers => @phone_numbers

app/views/clients/_patient_list.html.haml
%fieldset{:class => 'patients'}
  %legend Patients
  - unless client.patients.empty?
    = patient_select_list(client)
    %span{:class => 'or'} &mdash; or &mdash;
  = link_to "Create a new patient", new_client_patient_path(client), :remote => true

app/views/clients/_search_result.html.haml
= link_to edit_client_path(client) do
  .label
    = "Client"
  %strong
    = client.full_name
  %br
  %small{:class => 'address'}
    = address_for(client)

app/views/clients/create.js.erb
$('#client').replaceWith('<%= escape_javascript(render :partial => 'edit') %>');
<%= render 'layouts/flash', :flash => flash %>

app/views/clients/edit.html.haml
#patient
= render 'edit'

app/views/clients/edit.js.erb
$('#client').replaceWith('<%= escape_javascript(render :partial => 'edit') %>');
<%= render 'layouts/flash', :flash => flash %>

app/views/clients/new.html.haml
#patient
= render 'new'

app/views/clients/new.js.erb
$('#client').replaceWith('<%= escape_javascript(render :partial => 'new') %>');
<%= render 'layouts/flash', :flash => flash %>

app/views/clients/show.html.haml
= render 'navigation', :client => @client

#client-view

app/views/clients/update.js.erb
$('#client').replaceWith('<%= escape_javascript(render :partial => 'edit') %>');
<%= render 'layouts/flash', :flash => flash %>