config/routes.rb
Dinovet::Application.routes.draw do
  root :to => "clients#index"

  resources :diagnosis_categories, :except => [:show]
  resources :diagnoses, :except => [:show]

  resources :treatment_categories, :except => [:show]
  resources :treatments, :except => [:show]

  resources :species, :only => [:show]

  resources :clients, :except => [:show] do
    resources :patients, :only => [:new, :create, :update]
  end

  resources :employees

  resources :patients, :only => [:edit, :update] do
    resources :events, :only => [:index]
    resources :diagnosis_events, :only => [:new, :create]
    resources :treatment_plans,  :only => [:new, :create]
  end

  resource :search, :only => [:show]

end

app/models/event.rb
class Event
  include Mongoid::Document
  include Mongoid::Timestamps
  embedded_in :patient, :inverse_of => :events
  
  def type
    _type.sub("Event", "")
  end

  attr_reader :name
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :get_filter, :get_date_filter

  def index
    @patient = Patient.find(params[:patient_id])
    @events = @patient.events.created_between(*@date_filter).send(@filter)
  end

  protected
  def get_filter
    filter_pair = Event::FILTERS[params[:filter]]
    unless filter_pair.nil?
      @filter = filter_pair[:scope]
    else
      @filter = :all
    end
  end

  def get_date_filter
    unless params[:date_filter].blank?
      @date_filter = params[:date_filter].split('-')[0..1].map { |d| d.strip }
      @date_filter.map! { |d| Time.strptime(d, "%m/%d/%Y") }
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def select_tag_for_filter(model)
    options  = model::FILTERS.collect { |k, v| [v[:label], v[:scope]] }
    selected = params[:filter]
    select_tag("filter", options_for_select(options, selected))
  end

  def date_range_tag_for_filter
    value = params[:date_filter] || "Enter a date range"
    text_field_tag "date_filter", value, :class => :date_range_picker
  end
end

app/views/events/_event_row.html.haml
%tr{:class => cycle('odd', 'even')}
  %td{:class => 'date'}=l event_row.created_at, :format => :abbreviated
  %td
    = event_row.type
  %td
    = event_row.name
    %br
    %small
      = event_row.comment

app/views/events/_index.html.haml
= patient_panel(@patient, :History) do
  = form_tag patient_events_path(@patient), :method => :get, :remote => true, :class => :filter do
    = date_range_tag_for_filter
    = select_tag_for_filter(Event)
  %table{:class => :events}
    %thead
      %th Date
      %th Type
      %th Description
    %tbody
      = render :partial => 'event_row', :collection => @events

app/views/events/index.html.haml
= render 'index'

app/views/events/index.js.erb
$('#patient').replaceWith('<%= escape_javascript(render 'index') %>')