config/routes.rb
Dinovet::Application.routes.draw do
  root :to => "clients#index"

  resources :diagnosis_categories, :except => [:show]
  resources :diagnoses, :except => [:show]

  resources :treatment_categories, :except => [:show]
  resources :treatments, :except => [:show]

  resources :species, :only => [:show]

  resources :clients, :except => [:show] do
    resources :patients, :only => [:new, :create, :update]
  end

  resources :employees

  resources :patients, :only => [:edit, :update] do
    resources :events, :only => [:index]
    resources :diagnosis_events, :only => [:new, :create]
    resources :treatment_plans,  :only => [:new, :create]
  end

  resource :search, :only => [:show]

end

app/views/layouts/_flash.js.erb
<% unless flash[:notice].blank? %>
  $('#flash-notice').html('<%= flash[:notice] %>').show().delay(2000).fadeOut()
<% end %>

<% unless flash[:error].blank? %>
  $('#flash-error').html('<%= flash[:error] %>').show().delay(2000).fadeOut()
<% end %>

app/views/layouts/_panel.html.haml
- id       ||= nil
- title    ||= nil
- subtitle ||= nil
- links    ||= nil
- tab      ||= nil

.panel{:id => id}
  .header
    - unless title.nil?
      %h2=h title
    - unless subtitle.nil?
      %h3=h subtitle
    - unless links.nil?
      .tab-navigation
        %ul
          - links.each do |name, url|
            %li{:class => name == tab ? "selected" : ""}
              = link_to h(name), url, :remote => true

  .view
    = yield

app/views/layouts/application.html.haml
!!! 5
%html{html_attrs} 
 
  %head 
    %title Dinovet &rsaquo;
    = stylesheet_link_tag :all
    = javascript_include_tag :defaults
    = javascript_include_tag 'jquery-ui-1.8.5.custom.min.js'
    = javascript_include_tag 'selector.js'
    -if Rails.env == 'test' or Rails.env == 'cucumber' or Rails.env =='culerity'
      = javascript_include_tag 'culerity'
    = csrf_meta_tag
    :javascript
      var ROOT_PATH = '#{root_path}';

  %body 
 
    #header 
      %ul 
        %li
          = link_to "Diagnoses", diagnoses_path
        %li
          = link_to "Treatments", treatments_path
        %li
          = link_to "Employees", employees_path
        %li
          = link_to "Clients", clients_path

    = render 'searches/search_bar'

  = yield

  != error_message
  != notice_message